//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.02 at 01:34:43 PM IST 
//

package com.staples.pim.delegate.copyandprint.inbound.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;Attributes&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name=&quot;Attribute&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name=&quot;PimCore&quot;&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name=&quot;XPath&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                       &lt;element name=&quot;EndElement&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                       &lt;element name=&quot;Description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                       &lt;element name=&quot;properties&quot;&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name=&quot;Length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *                                                 &lt;element name=&quot;Datatype&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                                 &lt;element name=&quot;Required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                                 &lt;element name=&quot;Status&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                                 &lt;element name=&quot;Default&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name=&quot;Reference&quot;&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name=&quot;Index&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *                                                 &lt;element name=&quot;DependencyIndex&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                                 &lt;element name=&quot;DependencyValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                                 &lt;element name=&quot;NodeName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                                 &lt;element name=&quot;NodeLevel&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name=&quot;Step&quot;&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name=&quot;AttributeID&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                       &lt;element name=&quot;Attribute&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                       &lt;element name=&quot;Description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                       &lt;element name=&quot;properties&quot;&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name=&quot;Length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *                                                 &lt;element name=&quot;Datatype&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                                 &lt;element name=&quot;Required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                                 &lt;element name=&quot;Status&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                                 &lt;element name=&quot;Default&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name=&quot;Reference&quot;&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name=&quot;Index&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *                                                 &lt;element name=&quot;DependencyIndex&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                                 &lt;element name=&quot;DependencyValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "attributes" })
@XmlRootElement(name = "Mapping")
public class Mapping {

	@XmlElement(name = "Attributes", required = true)
	protected Mapping.Attributes	attributes;

	/**
	 * Gets the value of the attributes property.
	 * 
	 * @return possible object is {@link Mapping.Attributes }
	 * 
	 */
	public Mapping.Attributes getAttributes() {

		return attributes;
	}

	/**
	 * Sets the value of the attributes property.
	 * 
	 * @param value
	 *            allowed object is {@link Mapping.Attributes }
	 * 
	 */
	public void setAttributes(Mapping.Attributes value) {

		this.attributes = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name=&quot;Attribute&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *                 &lt;sequence&gt;
	 *                   &lt;element name=&quot;PimCore&quot;&gt;
	 *                     &lt;complexType&gt;
	 *                       &lt;complexContent&gt;
	 *                         &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *                           &lt;sequence&gt;
	 *                             &lt;element name=&quot;XPath&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                             &lt;element name=&quot;EndElement&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                             &lt;element name=&quot;Description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                             &lt;element name=&quot;properties&quot;&gt;
	 *                               &lt;complexType&gt;
	 *                                 &lt;complexContent&gt;
	 *                                   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *                                     &lt;sequence&gt;
	 *                                       &lt;element name=&quot;Length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
	 *                                       &lt;element name=&quot;Datatype&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                       &lt;element name=&quot;Required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                       &lt;element name=&quot;Status&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                       &lt;element name=&quot;Default&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                     &lt;/sequence&gt;
	 *                                   &lt;/restriction&gt;
	 *                                 &lt;/complexContent&gt;
	 *                               &lt;/complexType&gt;
	 *                             &lt;/element&gt;
	 *                             &lt;element name=&quot;Reference&quot;&gt;
	 *                               &lt;complexType&gt;
	 *                                 &lt;complexContent&gt;
	 *                                   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *                                     &lt;sequence&gt;
	 *                                       &lt;element name=&quot;Index&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
	 *                                       &lt;element name=&quot;DependencyIndex&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                       &lt;element name=&quot;DependencyValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                       &lt;element name=&quot;NodeName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                       &lt;element name=&quot;NodeLevel&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                     &lt;/sequence&gt;
	 *                                   &lt;/restriction&gt;
	 *                                 &lt;/complexContent&gt;
	 *                               &lt;/complexType&gt;
	 *                             &lt;/element&gt;
	 *                           &lt;/sequence&gt;
	 *                         &lt;/restriction&gt;
	 *                       &lt;/complexContent&gt;
	 *                     &lt;/complexType&gt;
	 *                   &lt;/element&gt;
	 *                   &lt;element name=&quot;Step&quot;&gt;
	 *                     &lt;complexType&gt;
	 *                       &lt;complexContent&gt;
	 *                         &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *                           &lt;sequence&gt;
	 *                             &lt;element name=&quot;AttributeID&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                             &lt;element name=&quot;Attribute&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                             &lt;element name=&quot;Description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                             &lt;element name=&quot;properties&quot;&gt;
	 *                               &lt;complexType&gt;
	 *                                 &lt;complexContent&gt;
	 *                                   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *                                     &lt;sequence&gt;
	 *                                       &lt;element name=&quot;Length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
	 *                                       &lt;element name=&quot;Datatype&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                       &lt;element name=&quot;Required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                       &lt;element name=&quot;Status&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                       &lt;element name=&quot;Default&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                     &lt;/sequence&gt;
	 *                                   &lt;/restriction&gt;
	 *                                 &lt;/complexContent&gt;
	 *                               &lt;/complexType&gt;
	 *                             &lt;/element&gt;
	 *                             &lt;element name=&quot;Reference&quot;&gt;
	 *                               &lt;complexType&gt;
	 *                                 &lt;complexContent&gt;
	 *                                   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *                                     &lt;sequence&gt;
	 *                                       &lt;element name=&quot;Index&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
	 *                                       &lt;element name=&quot;DependencyIndex&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                       &lt;element name=&quot;DependencyValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *                                     &lt;/sequence&gt;
	 *                                   &lt;/restriction&gt;
	 *                                 &lt;/complexContent&gt;
	 *                               &lt;/complexType&gt;
	 *                             &lt;/element&gt;
	 *                           &lt;/sequence&gt;
	 *                         &lt;/restriction&gt;
	 *                       &lt;/complexContent&gt;
	 *                     &lt;/complexType&gt;
	 *                   &lt;/element&gt;
	 *                 &lt;/sequence&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "attribute" })
	public static class Attributes {

		@XmlElement(name = "Attribute")
		protected List<Mapping.Attributes.Attribute>	attribute;

		/**
		 * Gets the value of the attribute property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the attribute property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getAttribute().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Mapping.Attributes.Attribute }
		 * 
		 * 
		 */
		public List<Mapping.Attributes.Attribute> getAttribute() {

			if (attribute == null) {
				attribute = new ArrayList<Mapping.Attributes.Attribute>();
			}
			return this.attribute;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
		 *       &lt;sequence&gt;
		 *         &lt;element name=&quot;PimCore&quot;&gt;
		 *           &lt;complexType&gt;
		 *             &lt;complexContent&gt;
		 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
		 *                 &lt;sequence&gt;
		 *                   &lt;element name=&quot;XPath&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                   &lt;element name=&quot;EndElement&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                   &lt;element name=&quot;Description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                   &lt;element name=&quot;properties&quot;&gt;
		 *                     &lt;complexType&gt;
		 *                       &lt;complexContent&gt;
		 *                         &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
		 *                           &lt;sequence&gt;
		 *                             &lt;element name=&quot;Length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
		 *                             &lt;element name=&quot;Datatype&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                             &lt;element name=&quot;Required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                             &lt;element name=&quot;Status&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                             &lt;element name=&quot;Default&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                           &lt;/sequence&gt;
		 *                         &lt;/restriction&gt;
		 *                       &lt;/complexContent&gt;
		 *                     &lt;/complexType&gt;
		 *                   &lt;/element&gt;
		 *                   &lt;element name=&quot;Reference&quot;&gt;
		 *                     &lt;complexType&gt;
		 *                       &lt;complexContent&gt;
		 *                         &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
		 *                           &lt;sequence&gt;
		 *                             &lt;element name=&quot;Index&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
		 *                             &lt;element name=&quot;DependencyIndex&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                             &lt;element name=&quot;DependencyValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                             &lt;element name=&quot;NodeName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                             &lt;element name=&quot;NodeLevel&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                           &lt;/sequence&gt;
		 *                         &lt;/restriction&gt;
		 *                       &lt;/complexContent&gt;
		 *                     &lt;/complexType&gt;
		 *                   &lt;/element&gt;
		 *                 &lt;/sequence&gt;
		 *               &lt;/restriction&gt;
		 *             &lt;/complexContent&gt;
		 *           &lt;/complexType&gt;
		 *         &lt;/element&gt;
		 *         &lt;element name=&quot;Step&quot;&gt;
		 *           &lt;complexType&gt;
		 *             &lt;complexContent&gt;
		 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
		 *                 &lt;sequence&gt;
		 *                   &lt;element name=&quot;AttributeID&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                   &lt;element name=&quot;Attribute&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                   &lt;element name=&quot;Description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                   &lt;element name=&quot;properties&quot;&gt;
		 *                     &lt;complexType&gt;
		 *                       &lt;complexContent&gt;
		 *                         &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
		 *                           &lt;sequence&gt;
		 *                             &lt;element name=&quot;Length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
		 *                             &lt;element name=&quot;Datatype&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                             &lt;element name=&quot;Required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                             &lt;element name=&quot;Status&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                             &lt;element name=&quot;Default&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                           &lt;/sequence&gt;
		 *                         &lt;/restriction&gt;
		 *                       &lt;/complexContent&gt;
		 *                     &lt;/complexType&gt;
		 *                   &lt;/element&gt;
		 *                   &lt;element name=&quot;Reference&quot;&gt;
		 *                     &lt;complexType&gt;
		 *                       &lt;complexContent&gt;
		 *                         &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
		 *                           &lt;sequence&gt;
		 *                             &lt;element name=&quot;Index&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
		 *                             &lt;element name=&quot;DependencyIndex&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                             &lt;element name=&quot;DependencyValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
		 *                           &lt;/sequence&gt;
		 *                         &lt;/restriction&gt;
		 *                       &lt;/complexContent&gt;
		 *                     &lt;/complexType&gt;
		 *                   &lt;/element&gt;
		 *                 &lt;/sequence&gt;
		 *               &lt;/restriction&gt;
		 *             &lt;/complexContent&gt;
		 *           &lt;/complexType&gt;
		 *         &lt;/element&gt;
		 *       &lt;/sequence&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "pimCore", "step" })
		public static class Attribute {

			@XmlElement(name = "PimCore", required = true)
			protected Mapping.Attributes.Attribute.PimCore	pimCore;
			@XmlElement(name = "Step", required = true)
			protected Mapping.Attributes.Attribute.Step		step;

			/**
			 * Gets the value of the pimCore property.
			 * 
			 * @return possible object is
			 *         {@link Mapping.Attributes.Attribute.PimCore }
			 * 
			 */
			public Mapping.Attributes.Attribute.PimCore getPimCore() {

				return pimCore;
			}

			/**
			 * Sets the value of the pimCore property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link Mapping.Attributes.Attribute.PimCore }
			 * 
			 */
			public void setPimCore(Mapping.Attributes.Attribute.PimCore value) {

				this.pimCore = value;
			}

			/**
			 * Gets the value of the step property.
			 * 
			 * @return possible object is
			 *         {@link Mapping.Attributes.Attribute.Step }
			 * 
			 */
			public Mapping.Attributes.Attribute.Step getStep() {

				return step;
			}

			/**
			 * Sets the value of the step property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link Mapping.Attributes.Attribute.Step }
			 * 
			 */
			public void setStep(Mapping.Attributes.Attribute.Step value) {

				this.step = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType&gt;
			 *   &lt;complexContent&gt;
			 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
			 *       &lt;sequence&gt;
			 *         &lt;element name=&quot;XPath&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *         &lt;element name=&quot;EndElement&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *         &lt;element name=&quot;Description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *         &lt;element name=&quot;properties&quot;&gt;
			 *           &lt;complexType&gt;
			 *             &lt;complexContent&gt;
			 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
			 *                 &lt;sequence&gt;
			 *                   &lt;element name=&quot;Length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
			 *                   &lt;element name=&quot;Datatype&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                   &lt;element name=&quot;Required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                   &lt;element name=&quot;Status&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                   &lt;element name=&quot;Default&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                 &lt;/sequence&gt;
			 *               &lt;/restriction&gt;
			 *             &lt;/complexContent&gt;
			 *           &lt;/complexType&gt;
			 *         &lt;/element&gt;
			 *         &lt;element name=&quot;Reference&quot;&gt;
			 *           &lt;complexType&gt;
			 *             &lt;complexContent&gt;
			 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
			 *                 &lt;sequence&gt;
			 *                   &lt;element name=&quot;Index&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
			 *                   &lt;element name=&quot;DependencyIndex&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                   &lt;element name=&quot;DependencyValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                   &lt;element name=&quot;NodeName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                   &lt;element name=&quot;NodeLevel&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                 &lt;/sequence&gt;
			 *               &lt;/restriction&gt;
			 *             &lt;/complexContent&gt;
			 *           &lt;/complexType&gt;
			 *         &lt;/element&gt;
			 *       &lt;/sequence&gt;
			 *     &lt;/restriction&gt;
			 *   &lt;/complexContent&gt;
			 * &lt;/complexType&gt;
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "xPath", "endElement", "description", "properties", "reference" })
			public static class PimCore {

				@XmlElement(name = "XPath", required = true)
				protected String											xPath;
				@XmlElement(name = "EndElement", required = true)
				protected String											endElement;
				@XmlElement(name = "Description", required = true)
				protected String											description;
				@XmlElement(required = true)
				protected Mapping.Attributes.Attribute.PimCore.Properties	properties;
				@XmlElement(name = "Reference", required = true)
				protected Mapping.Attributes.Attribute.PimCore.Reference	reference;

				/**
				 * Gets the value of the xPath property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getXPath() {

					return xPath;
				}

				/**
				 * Sets the value of the xPath property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setXPath(String value) {

					this.xPath = value;
				}

				/**
				 * Gets the value of the endElement property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getEndElement() {

					return endElement;
				}

				/**
				 * Sets the value of the endElement property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setEndElement(String value) {

					this.endElement = value;
				}

				/**
				 * Gets the value of the description property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getDescription() {

					return description;
				}

				/**
				 * Sets the value of the description property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setDescription(String value) {

					this.description = value;
				}

				/**
				 * Gets the value of the properties property.
				 * 
				 * @return possible object is
				 *         {@link Mapping.Attributes.Attribute.PimCore.Properties }
				 * 
				 */
				public Mapping.Attributes.Attribute.PimCore.Properties getProperties() {

					return properties;
				}

				/**
				 * Sets the value of the properties property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link Mapping.Attributes.Attribute.PimCore.Properties }
				 * 
				 */
				public void setProperties(Mapping.Attributes.Attribute.PimCore.Properties value) {

					this.properties = value;
				}

				/**
				 * Gets the value of the reference property.
				 * 
				 * @return possible object is
				 *         {@link Mapping.Attributes.Attribute.PimCore.Reference }
				 * 
				 */
				public Mapping.Attributes.Attribute.PimCore.Reference getReference() {

					return reference;
				}

				/**
				 * Sets the value of the reference property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link Mapping.Attributes.Attribute.PimCore.Reference }
				 * 
				 */
				public void setReference(Mapping.Attributes.Attribute.PimCore.Reference value) {

					this.reference = value;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType&gt;
				 *   &lt;complexContent&gt;
				 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
				 *       &lt;sequence&gt;
				 *         &lt;element name=&quot;Length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
				 *         &lt;element name=&quot;Datatype&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *         &lt;element name=&quot;Required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *         &lt;element name=&quot;Status&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *         &lt;element name=&quot;Default&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *       &lt;/sequence&gt;
				 *     &lt;/restriction&gt;
				 *   &lt;/complexContent&gt;
				 * &lt;/complexType&gt;
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "length", "datatype", "required", "status", "_default" })
				public static class Properties {

					@XmlElement(name = "Length")
					protected int		length;
					@XmlElement(name = "Datatype", required = true)
					protected String	datatype;
					@XmlElement(name = "Required", required = true)
					protected String	required;
					@XmlElement(name = "Status", required = true)
					protected String	status;
					@XmlElement(name = "Default", required = true)
					protected String	_default;

					/**
					 * Gets the value of the length property.
					 * 
					 */
					public int getLength() {

						return length;
					}

					/**
					 * Sets the value of the length property.
					 * 
					 */
					public void setLength(int value) {

						this.length = value;
					}

					/**
					 * Gets the value of the datatype property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getDatatype() {

						return datatype;
					}

					/**
					 * Sets the value of the datatype property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setDatatype(String value) {

						this.datatype = value;
					}

					/**
					 * Gets the value of the required property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getRequired() {

						return required;
					}

					/**
					 * Sets the value of the required property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setRequired(String value) {

						this.required = value;
					}

					/**
					 * Gets the value of the status property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getStatus() {

						return status;
					}

					/**
					 * Sets the value of the status property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setStatus(String value) {

						this.status = value;
					}

					/**
					 * Gets the value of the default property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getDefault() {

						return _default;
					}

					/**
					 * Sets the value of the default property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setDefault(String value) {

						this._default = value;
					}

				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType&gt;
				 *   &lt;complexContent&gt;
				 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
				 *       &lt;sequence&gt;
				 *         &lt;element name=&quot;Index&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
				 *         &lt;element name=&quot;DependencyIndex&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *         &lt;element name=&quot;DependencyValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *         &lt;element name=&quot;NodeName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *         &lt;element name=&quot;NodeLevel&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *       &lt;/sequence&gt;
				 *     &lt;/restriction&gt;
				 *   &lt;/complexContent&gt;
				 * &lt;/complexType&gt;
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "index", "dependencyIndex", "dependencyValue", "nodeName", "nodeLevel" })
				public static class Reference {

					@XmlElement(name = "Index")
					protected int		index;
					@XmlElement(name = "DependencyIndex", required = true)
					protected String	dependencyIndex;
					@XmlElement(name = "DependencyValue", required = true)
					protected String	dependencyValue;
					@XmlElement(name = "NodeName", required = true)
					protected String	nodeName;
					@XmlElement(name = "NodeLevel", required = true)
					protected String	nodeLevel;

					/**
					 * Gets the value of the index property.
					 * 
					 */
					public int getIndex() {

						return index;
					}

					/**
					 * Sets the value of the index property.
					 * 
					 */
					public void setIndex(int value) {

						this.index = value;
					}

					/**
					 * Gets the value of the dependencyIndex property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getDependencyIndex() {

						return dependencyIndex;
					}

					/**
					 * Sets the value of the dependencyIndex property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setDependencyIndex(String value) {

						this.dependencyIndex = value;
					}

					/**
					 * Gets the value of the dependencyValue property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getDependencyValue() {

						return dependencyValue;
					}

					/**
					 * Sets the value of the dependencyValue property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setDependencyValue(String value) {

						this.dependencyValue = value;
					}

					/**
					 * Gets the value of the nodeName property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getNodeName() {

						return nodeName;
					}

					/**
					 * Sets the value of the nodeName property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setNodeName(String value) {

						this.nodeName = value;
					}

					/**
					 * Gets the value of the nodeLevel property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getNodeLevel() {

						return nodeLevel;
					}

					/**
					 * Sets the value of the nodeLevel property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setNodeLevel(String value) {

						this.nodeLevel = value;
					}

				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType&gt;
			 *   &lt;complexContent&gt;
			 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
			 *       &lt;sequence&gt;
			 *         &lt;element name=&quot;AttributeID&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *         &lt;element name=&quot;Attribute&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *         &lt;element name=&quot;Description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *         &lt;element name=&quot;properties&quot;&gt;
			 *           &lt;complexType&gt;
			 *             &lt;complexContent&gt;
			 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
			 *                 &lt;sequence&gt;
			 *                   &lt;element name=&quot;Length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
			 *                   &lt;element name=&quot;Datatype&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                   &lt;element name=&quot;Required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                   &lt;element name=&quot;Status&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                   &lt;element name=&quot;Default&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                 &lt;/sequence&gt;
			 *               &lt;/restriction&gt;
			 *             &lt;/complexContent&gt;
			 *           &lt;/complexType&gt;
			 *         &lt;/element&gt;
			 *         &lt;element name=&quot;Reference&quot;&gt;
			 *           &lt;complexType&gt;
			 *             &lt;complexContent&gt;
			 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
			 *                 &lt;sequence&gt;
			 *                   &lt;element name=&quot;Index&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
			 *                   &lt;element name=&quot;DependencyIndex&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                   &lt;element name=&quot;DependencyValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
			 *                 &lt;/sequence&gt;
			 *               &lt;/restriction&gt;
			 *             &lt;/complexContent&gt;
			 *           &lt;/complexType&gt;
			 *         &lt;/element&gt;
			 *       &lt;/sequence&gt;
			 *     &lt;/restriction&gt;
			 *   &lt;/complexContent&gt;
			 * &lt;/complexType&gt;
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "attributeID", "attribute", "description", "properties", "reference" })
			public static class Step {

				@XmlElement(name = "AttributeID", required = true)
				protected String										attributeID;
				@XmlElement(name = "Attribute", required = true)
				protected String										attribute;
				@XmlElement(name = "Description", required = true)
				protected String										description;
				@XmlElement(required = true)
				protected Mapping.Attributes.Attribute.Step.Properties	properties;
				@XmlElement(name = "Reference", required = true)
				protected Mapping.Attributes.Attribute.Step.Reference	reference;

				/**
				 * Gets the value of the attributeID property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getAttributeID() {

					return attributeID;
				}

				/**
				 * Sets the value of the attributeID property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setAttributeID(String value) {

					this.attributeID = value;
				}

				/**
				 * Gets the value of the attribute property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getAttribute() {

					return attribute;
				}

				/**
				 * Sets the value of the attribute property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setAttribute(String value) {

					this.attribute = value;
				}

				/**
				 * Gets the value of the description property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getDescription() {

					return description;
				}

				/**
				 * Sets the value of the description property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setDescription(String value) {

					this.description = value;
				}

				/**
				 * Gets the value of the properties property.
				 * 
				 * @return possible object is
				 *         {@link Mapping.Attributes.Attribute.Step.Properties }
				 * 
				 */
				public Mapping.Attributes.Attribute.Step.Properties getProperties() {

					return properties;
				}

				/**
				 * Sets the value of the properties property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link Mapping.Attributes.Attribute.Step.Properties }
				 * 
				 */
				public void setProperties(Mapping.Attributes.Attribute.Step.Properties value) {

					this.properties = value;
				}

				/**
				 * Gets the value of the reference property.
				 * 
				 * @return possible object is
				 *         {@link Mapping.Attributes.Attribute.Step.Reference }
				 * 
				 */
				public Mapping.Attributes.Attribute.Step.Reference getReference() {

					return reference;
				}

				/**
				 * Sets the value of the reference property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link Mapping.Attributes.Attribute.Step.Reference }
				 * 
				 */
				public void setReference(Mapping.Attributes.Attribute.Step.Reference value) {

					this.reference = value;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType&gt;
				 *   &lt;complexContent&gt;
				 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
				 *       &lt;sequence&gt;
				 *         &lt;element name=&quot;Length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
				 *         &lt;element name=&quot;Datatype&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *         &lt;element name=&quot;Required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *         &lt;element name=&quot;Status&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *         &lt;element name=&quot;Default&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *       &lt;/sequence&gt;
				 *     &lt;/restriction&gt;
				 *   &lt;/complexContent&gt;
				 * &lt;/complexType&gt;
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "length", "datatype", "required", "status", "_default" })
				public static class Properties {

					@XmlElement(name = "Length")
					protected int		length;
					@XmlElement(name = "Datatype", required = true)
					protected String	datatype;
					@XmlElement(name = "Required", required = true)
					protected String	required;
					@XmlElement(name = "Status", required = true)
					protected String	status;
					@XmlElement(name = "Default", required = true)
					protected String	_default;

					/**
					 * Gets the value of the length property.
					 * 
					 */
					public int getLength() {

						return length;
					}

					/**
					 * Sets the value of the length property.
					 * 
					 */
					public void setLength(int value) {

						this.length = value;
					}

					/**
					 * Gets the value of the datatype property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getDatatype() {

						return datatype;
					}

					/**
					 * Sets the value of the datatype property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setDatatype(String value) {

						this.datatype = value;
					}

					/**
					 * Gets the value of the required property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getRequired() {

						return required;
					}

					/**
					 * Sets the value of the required property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setRequired(String value) {

						this.required = value;
					}

					/**
					 * Gets the value of the status property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getStatus() {

						return status;
					}

					/**
					 * Sets the value of the status property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setStatus(String value) {

						this.status = value;
					}

					/**
					 * Gets the value of the default property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getDefault() {

						return _default;
					}

					/**
					 * Sets the value of the default property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setDefault(String value) {

						this._default = value;
					}

				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType&gt;
				 *   &lt;complexContent&gt;
				 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
				 *       &lt;sequence&gt;
				 *         &lt;element name=&quot;Index&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
				 *         &lt;element name=&quot;DependencyIndex&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *         &lt;element name=&quot;DependencyValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
				 *       &lt;/sequence&gt;
				 *     &lt;/restriction&gt;
				 *   &lt;/complexContent&gt;
				 * &lt;/complexType&gt;
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "index", "dependencyIndex", "dependencyValue" })
				public static class Reference {

					@XmlElement(name = "Index")
					protected int		index;
					@XmlElement(name = "DependencyIndex", required = true)
					protected String	dependencyIndex;
					@XmlElement(name = "DependencyValue", required = true)
					protected String	dependencyValue;

					/**
					 * Gets the value of the index property.
					 * 
					 */
					public int getIndex() {

						return index;
					}

					/**
					 * Sets the value of the index property.
					 * 
					 */
					public void setIndex(int value) {

						this.index = value;
					}

					/**
					 * Gets the value of the dependencyIndex property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getDependencyIndex() {

						return dependencyIndex;
					}

					/**
					 * Sets the value of the dependencyIndex property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setDependencyIndex(String value) {

						this.dependencyIndex = value;
					}

					/**
					 * Gets the value of the dependencyValue property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getDependencyValue() {

						return dependencyValue;
					}

					/**
					 * Sets the value of the dependencyValue property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setDependencyValue(String value) {

						this.dependencyValue = value;
					}

				}

			}

		}

	}

}
