package com.staples.pcm.springbatch.common.beans;
//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//Any modifications to this file will be lost upon recompilation of the source schema.
//Generated on: 2014.05.31 at 09:59:54 PM EDT
//


import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
* <p>Java class for anonymous complex type.
*
* <p>The following schema fragment specifies the expected content contained within this class.
*
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="Products">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="Product" maxOccurs="unbounded" minOccurs="0">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;sequence>
*                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                             &lt;element name="ClassificationReference" maxOccurs="unbounded" minOccurs="0">
*                               &lt;complexType>
*                                 &lt;simpleContent>
*                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
*                                     &lt;attribute name="ClassificationID" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                     &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                   &lt;/extension>
*                                 &lt;/simpleContent>
*                               &lt;/complexType>
*                             &lt;/element>
*                             &lt;element name="AssetCrossReference">
*                               &lt;complexType>
*                                 &lt;simpleContent>
*                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
*                                     &lt;attribute name="AssetID" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                     &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                   &lt;/extension>
*                                 &lt;/simpleContent>
*                               &lt;/complexType>
*                             &lt;/element>
*                             &lt;element name="Values">
*                               &lt;complexType>
*                                 &lt;complexContent>
*                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                                     &lt;sequence>
*                                       &lt;element name="Value" maxOccurs="unbounded" minOccurs="0">
*                                         &lt;complexType>
*                                           &lt;simpleContent>
*                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
*                                               &lt;attribute name="AttributeID" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                               &lt;attribute name="UnitID" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                               &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                               &lt;attribute name="Derived" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                             &lt;/extension>
*                                           &lt;/simpleContent>
*                                         &lt;/complexType>
*                                       &lt;/element>
*                                     &lt;/sequence>
*                                   &lt;/restriction>
*                                 &lt;/complexContent>
*                               &lt;/complexType>
*                             &lt;/element>
*                           &lt;/sequence>
*                           &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
*                           &lt;attribute name="UserTypeID" type="{http://www.w3.org/2001/XMLSchema}string" />
*                           &lt;attribute name="ParentID" type="{http://www.w3.org/2001/XMLSchema}string" />
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*       &lt;/sequence>
*       &lt;attribute name="ExportTime" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="ExportContext" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="ContextID" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="WorkspaceID" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="UseContextLocale" type="{http://www.w3.org/2001/XMLSchema}string" />
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
*
*
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {})
@XmlRootElement(name = "STEP-ProductInformation")
public class STEPProductInformation {

 @XmlElement(name = "Products")
 protected STEPProductInformation.Products products;
 @XmlAttribute(name = "ExportTime")
 protected String exportTime;
 @XmlAttribute(name = "ExportContext")
 protected String exportContext;
 @XmlAttribute(name = "ContextID")
 protected String contextID;
 @XmlAttribute(name = "WorkspaceID")
 protected String workspaceID;
 @XmlAttribute(name = "UseContextLocale")
 protected String useContextLocale;
 @XmlAttribute(name = "AutoApprove")
 protected String autoApprove;

 /**
  * Gets the value of the products property.
  *
  * @return
  *     possible object is
  *     {@link STEPProductInformation.Products }
  *
  */
 public STEPProductInformation.Products getProducts() {
     return products;
 }

 /**
  * Sets the value of the products property.
  *
  * @param value
  *     allowed object is
  *     {@link STEPProductInformation.Products }
  *
  */
 public void setProducts(STEPProductInformation.Products value) {
     this.products = value;
 }

 /**
  * Gets the value of the exportTime property.
  *
  * @return
  *     possible object is
  *     {@link String }
  *
  */
 public String getExportTime() {
     return exportTime;
 }

 /**
  * Sets the value of the exportTime property.
  *
  * @param value
  *     allowed object is
  *     {@link String }
  *
  */
 public void setExportTime(String value) {
     this.exportTime = value;
 }

 /**
  * Gets the value of the exportContext property.
  *
  * @return
  *     possible object is
  *     {@link String }
  *
  */
 public String getExportContext() {
     return exportContext;
 }

 /**
  * Sets the value of the exportContext property.
  *
  * @param value
  *     allowed object is
  *     {@link String }
  *
  */
 public void setExportContext(String value) {
     this.exportContext = value;
 }

 /**
  * Gets the value of the contextID property.
  *
  * @return
  *     possible object is
  *     {@link String }
  *
  */
 public String getContextID() {
     return contextID;
 }

 /**
  * Sets the value of the contextID property.
  *
  * @param value
  *     allowed object is
  *     {@link String }
  *
  */
 public void setContextID(String value) {
     this.contextID = value;
 }
 
 /**
  * Gets the value of the autoApprove property.
  *
  * @return
  *     possible object is
  *     {@link String }
  *
  */
 public String getAutoApprove() {
     return autoApprove;
 }

 /**
  * Sets the value of the autoApprove property.
  *
  * @param value
  *     allowed object is
  *     {@link String }
  *
  */
 public void setAutoApprove(String value) {
     this.autoApprove = value;
 }
 
 

 /**
  * Gets the value of the workspaceID property.
  *
  * @return
  *     possible object is
  *     {@link String }
  *
  */
 public String getWorkspaceID() {
     return workspaceID;
 }

 /**
  * Sets the value of the workspaceID property.
  *
  * @param value
  *     allowed object is
  *     {@link String }
  *
  */
 public void setWorkspaceID(String value) {
     this.workspaceID = value;
 }

 /**
  * Gets the value of the useContextLocale property.
  *
  * @return
  *     possible object is
  *     {@link String }
  *
  */
 public String getUseContextLocale() {
     return useContextLocale;
 }

 /**
  * Sets the value of the useContextLocale property.
  *
  * @param value
  *     allowed object is
  *     {@link String }
  *
  */
 public void setUseContextLocale(String value) {
     this.useContextLocale = value;
 }


 /**
  * <p>Java class for anonymous complex type.
  *
  * <p>The following schema fragment specifies the expected content contained within this class.
  *
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="Product" maxOccurs="unbounded" minOccurs="0">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *                   &lt;element name="ClassificationReference" maxOccurs="unbounded" minOccurs="0">
  *                     &lt;complexType>
  *                       &lt;simpleContent>
  *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
  *                           &lt;attribute name="ClassificationID" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                           &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                         &lt;/extension>
  *                       &lt;/simpleContent>
  *                     &lt;/complexType>
  *                   &lt;/element>
  *                   &lt;element name="AssetCrossReference">
  *                     &lt;complexType>
  *                       &lt;simpleContent>
  *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
  *                           &lt;attribute name="AssetID" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                           &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                         &lt;/extension>
  *                       &lt;/simpleContent>
  *                     &lt;/complexType>
  *                   &lt;/element>
  *                   &lt;element name="Values">
  *                     &lt;complexType>
  *                       &lt;complexContent>
  *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                           &lt;sequence>
  *                             &lt;element name="Value" maxOccurs="unbounded" minOccurs="0">
  *                               &lt;complexType>
  *                                 &lt;simpleContent>
  *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
  *                                     &lt;attribute name="AttributeID" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                                     &lt;attribute name="UnitID" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                                     &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                                     &lt;attribute name="Derived" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                                   &lt;/extension>
  *                                 &lt;/simpleContent>
  *                               &lt;/complexType>
  *                             &lt;/element>
  *                           &lt;/sequence>
  *                         &lt;/restriction>
  *                       &lt;/complexContent>
  *                     &lt;/complexType>
  *                   &lt;/element>
  *                 &lt;/sequence>
  *                 &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                 &lt;attribute name="UserTypeID" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                 &lt;attribute name="ParentID" type="{http://www.w3.org/2001/XMLSchema}string" />
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  *
  *
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {})
 public static class Products {

     @XmlElement(name = "Product")
     protected List<STEPProductInformation.Products.Product> product;

     /**
      * Gets the value of the product property.
      *
      * <p>
      * This accessor method returns a reference to the live list,
      * not a snapshot. Therefore any modification you make to the
      * returned list will be present inside the JAXB object.
      * This is why there is not a <CODE>set</CODE> method for the product property.
      *
      * <p>
      * For example, to add a new item, do as follows:
      * <pre>
      *    getProduct().add(newItem);
      * </pre>
      *
      *
      * <p>
      * Objects of the following type(s) are allowed in the list
      * {@link STEPProductInformation.Products.Product }
      *
      *
      */
     public List<STEPProductInformation.Products.Product> getProduct() {
         if (product == null) {
             product = new ArrayList<STEPProductInformation.Products.Product>();
         }
         return this.product;
     }


     /**
      * <p>Java class for anonymous complex type.
      *
      * <p>The following schema fragment specifies the expected content contained within this class.
      *
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
      *         &lt;element name="ClassificationReference" maxOccurs="unbounded" minOccurs="0">
      *           &lt;complexType>
      *             &lt;simpleContent>
      *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
      *                 &lt;attribute name="ClassificationID" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                 &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
      *               &lt;/extension>
      *             &lt;/simpleContent>
      *           &lt;/complexType>
      *         &lt;/element>
      *         &lt;element name="AssetCrossReference">
      *           &lt;complexType>
      *             &lt;simpleContent>
      *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
      *                 &lt;attribute name="AssetID" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                 &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
      *               &lt;/extension>
      *             &lt;/simpleContent>
      *           &lt;/complexType>
      *         &lt;/element>
      *         &lt;element name="Values">
      *           &lt;complexType>
      *             &lt;complexContent>
      *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *                 &lt;sequence>
      *                   &lt;element name="Value" maxOccurs="unbounded" minOccurs="0">
      *                     &lt;complexType>
      *                       &lt;simpleContent>
      *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
      *                           &lt;attribute name="AttributeID" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                           &lt;attribute name="UnitID" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                           &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                           &lt;attribute name="Derived" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                         &lt;/extension>
      *                       &lt;/simpleContent>
      *                     &lt;/complexType>
      *                   &lt;/element>
      *                 &lt;/sequence>
      *               &lt;/restriction>
      *             &lt;/complexContent>
      *           &lt;/complexType>
      *         &lt;/element>
      *       &lt;/sequence>
      *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
      *       &lt;attribute name="UserTypeID" type="{http://www.w3.org/2001/XMLSchema}string" />
      *       &lt;attribute name="ParentID" type="{http://www.w3.org/2001/XMLSchema}string" />
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      *
      *
      */
     @XmlRootElement(name = "Product")
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {})
     public static class Product {
    	 
    	 @XmlElement(name = "KeyValue", required = true)
    	 protected STEPProductInformation.Products.Product.KeyValue keyValue;
         @XmlElement(name = "Name", required = true)
         protected String name;
         @XmlElement(name = "ClassificationReference")
         protected List<STEPProductInformation.Products.Product.ClassificationReference> classificationReference;
         @XmlElement(name = "AssetCrossReference", required = true)
         protected STEPProductInformation.Products.Product.AssetCrossReference assetCrossReference;
         @XmlElement(name = "Values", required = true)
         protected STEPProductInformation.Products.Product.Values values;
         @XmlAttribute(name = "ID")
         protected String id;
         @XmlAttribute(name = "UserTypeID")
         protected String userTypeID;
         @XmlAttribute(name = "ParentID")
         protected String parentID;

         /**
          * Gets the value of the name property.
          *
          * @return
          *     possible object is
          *     {@link String }
          *
          */
         public String getName() {
             return name;
         }

         /**
          * Sets the value of the name property.
          *
          * @param value
          *     allowed object is
          *     {@link String }
          *
          */
         public void setName(String value) {
             this.name = value;
         }

         /**
          * Gets the value of the classificationReference property.
          *
          * <p>
          * This accessor method returns a reference to the live list,
          * not a snapshot. Therefore any modification you make to the
          * returned list will be present inside the JAXB object.
          * This is why there is not a <CODE>set</CODE> method for the classificationReference property.
          *
          * <p>
          * For example, to add a new item, do as follows:
          * <pre>
          *    getClassificationReference().add(newItem);
          * </pre>
          *
          *
          * <p>
          * Objects of the following type(s) are allowed in the list
          * {@link STEPProductInformation.Products.Product.ClassificationReference }
          *
          *
          */
         public List<STEPProductInformation.Products.Product.ClassificationReference> getClassificationReference() {
             if (classificationReference == null) {
                 classificationReference = new ArrayList<STEPProductInformation.Products.Product.ClassificationReference>();
             }
             return this.classificationReference;
         }

         /**
          * Gets the value of the assetCrossReference property.
          *
          * @return
          *     possible object is
          *     {@link STEPProductInformation.Products.Product.AssetCrossReference }
          *
          */
         public STEPProductInformation.Products.Product.AssetCrossReference getAssetCrossReference() {
             return assetCrossReference;
         }

         /**
          * Sets the value of the assetCrossReference property.
          *
          * @param value
          *     allowed object is
          *     {@link STEPProductInformation.Products.Product.AssetCrossReference }
          *
          */
         public void setAssetCrossReference(STEPProductInformation.Products.Product.AssetCrossReference value) {
             this.assetCrossReference = value;
         }

         /**
          * Gets the value of the values property.
          *
          * @return
          *     possible object is
          *     {@link STEPProductInformation.Products.Product.Values }
          *
          */
         public STEPProductInformation.Products.Product.Values getValues() {
             return values;
         }

         /**
          * Sets the value of the values property.
          *
          * @param value
          *     allowed object is
          *     {@link STEPProductInformation.Products.Product.Values }
          *
          */
         public void setValues(STEPProductInformation.Products.Product.Values value) {
             this.values = value;
         }

         
         public STEPProductInformation.Products.Product.KeyValue getKeyValue() {
             return keyValue;
         }

         /**
          * Sets the value of the KeyValue property.
          *
          * @param value
          *     allowed object is
          *     {@link STEPProductInformation.Products.Product.KeyValue }
          *
          */
         public void setKeyValue(STEPProductInformation.Products.Product.KeyValue keyValue) {
             this.keyValue = keyValue;
         }
         
         /**
          * Gets the value of the id property.
          *
          * @return
          *     possible object is
          *     {@link String }
          *
          */
         public String getID() {
             return id;
         }

         /**
          * Sets the value of the id property.
          *
          * @param value
          *     allowed object is
          *     {@link String }
          *
          */
         public void setID(String value) {
             this.id = value;
         }

         /**
          * Gets the value of the userTypeID property.
          *
          * @return
          *     possible object is
          *     {@link String }
          *
          */
         public String getUserTypeID() {
             return userTypeID;
         }

         /**
          * Sets the value of the userTypeID property.
          *
          * @param value
          *     allowed object is
          *     {@link String }
          *
          */
         public void setUserTypeID(String value) {
             this.userTypeID = value;
         }

         /**
          * Gets the value of the parentID property.
          *
          * @return
          *     possible object is
          *     {@link String }
          *
          */
         public String getParentID() {
             return parentID;
         }

         /**
          * Sets the value of the parentID property.
          *
          * @param value
          *     allowed object is
          *     {@link String }
          *
          */
         public void setParentID(String value) {
             this.parentID = value;
         }


         /**
          * <p>Java class for anonymous complex type.
          *
          * <p>The following schema fragment specifies the expected content contained within this class.
          *
          * <pre>
          * &lt;complexType>
          *   &lt;simpleContent>
          *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
          *       &lt;attribute name="AssetID" type="{http://www.w3.org/2001/XMLSchema}string" />
          *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
          *     &lt;/extension>
          *   &lt;/simpleContent>
          * &lt;/complexType>
          * </pre>
          *
          *
          */
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = {})
         public static class AssetCrossReference {

             @XmlValue
             protected String value;
             @XmlAttribute(name = "AssetID")
             protected String assetID;
             @XmlAttribute(name = "Type")
             protected String type;

             /**
              * Gets the value of the value property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getValue() {
                 return value;
             }

             /**
              * Sets the value of the value property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setValue(String value) {
                 this.value = value;
             }

             /**
              * Gets the value of the assetID property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getAssetID() {
                 return assetID;
             }

             /**
              * Sets the value of the assetID property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setAssetID(String value) {
                 this.assetID = value;
             }

             /**
              * Gets the value of the type property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getType() {
                 return type;
             }

             /**
              * Sets the value of the type property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setType(String value) {
                 this.type = value;
             }

         }

         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = {})
         public static class ProductCrossReference {

             @XmlElement(name = "Product")
             public STEPProductInformation.Products.Product product;
             @XmlAttribute(name = "ProductID")
             protected String productID;
             @XmlAttribute(name = "Type")
             protected String type;
             
             /**
              * Gets the value of the value property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public STEPProductInformation.Products.Product getProduct() {
                 return product;
             }

             /**
              * Sets the value of the value property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setValue(STEPProductInformation.Products.Product product) {
                 this.product = product;
             }

             /**
              * Gets the value of the assetID property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getProductID() {
                 return productID;
             }

             /**
              * Sets the value of the assetID property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setProductID(String value) {
                 this.productID = value;
             }

             /**
              * Gets the value of the type property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getType() {
                 return type;
             }

             /**
              * Sets the value of the type property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setType(String value) {
                 this.type = value;
             }

         }

         /**
          * <p>Java class for anonymous complex type.
          *
          * <p>The following schema fragment specifies the expected content contained within this class.
          *
          * <pre>
          * &lt;complexType>
          *   &lt;simpleContent>
          *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
          *       &lt;attribute name="ClassificationID" type="{http://www.w3.org/2001/XMLSchema}string" />
          *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
          *     &lt;/extension>
          *   &lt;/simpleContent>
          * &lt;/complexType>
          * </pre>
          *
          *
          */
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = {})
         public static class ClassificationReference {

             @XmlValue
             protected String value;
             @XmlAttribute(name = "ClassificationID")
             protected String classificationID;
             @XmlAttribute(name = "Type")
             protected String type;

             /**
              * Gets the value of the value property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getValue() {
                 return value;
             }

             /**
              * Sets the value of the value property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setValue(String value) {
                 this.value = value;
             }

             /**
              * Gets the value of the classificationID property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getClassificationID() {
                 return classificationID;
             }

             /**
              * Sets the value of the classificationID property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setClassificationID(String value) {
                 this.classificationID = value;
             }

             /**
              * Gets the value of the type property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getType() {
                 return type;
             }

             /**
              * Sets the value of the type property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setType(String value) {
                 this.type = value;
             }

         }


         /**
          * <p>Java class for anonymous complex type.
          *
          * <p>The following schema fragment specifies the expected content contained within this class.
          *
          * <pre>
          * &lt;complexType>
          *   &lt;complexContent>
          *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
          *       &lt;sequence>
          *         &lt;element name="Value" maxOccurs="unbounded" minOccurs="0">
          *           &lt;complexType>
          *             &lt;simpleContent>
          *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
          *                 &lt;attribute name="AttributeID" type="{http://www.w3.org/2001/XMLSchema}string" />
          *                 &lt;attribute name="UnitID" type="{http://www.w3.org/2001/XMLSchema}string" />
          *                 &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
          *                 &lt;attribute name="Derived" type="{http://www.w3.org/2001/XMLSchema}string" />
          *               &lt;/extension>
          *             &lt;/simpleContent>
          *           &lt;/complexType>
          *         &lt;/element>
          *       &lt;/sequence>
          *     &lt;/restriction>
          *   &lt;/complexContent>
          * &lt;/complexType>
          * </pre>
          *
          *
          */
         
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = {})
         public static class KeyValue {
 
             @XmlValue
             protected String value;
             @XmlAttribute(name = "KeyID")
             protected String keyId;
             
             public String getValue() {
                 return value;
             }

             /**
              * Sets the value of the value property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setValue(String value) {
                 this.value = value;
             }
             
             /**
              * Gets the value of the attributeID property.
              *
              * @return
              *     possible object is
              *     {@link String }
              *
              */
             public String getKeyId() {
                 return keyId;
             }

             /**
              * Sets the value of the attributeID property.
              *
              * @param value
              *     allowed object is
              *     {@link String }
              *
              */
             public void setKeyId(String keyId) {
                 this.keyId = keyId;
             }
             
         }
         
         
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = {})
         public static class Values {

             @XmlElement(name = "Value")
             protected List<STEPProductInformation.Products.Product.Values.Value> value;

             /**
              * Gets the value of the value property.
              *
              * <p>
              * This accessor method returns a reference to the live list,
              * not a snapshot. Therefore any modification you make to the
              * returned list will be present inside the JAXB object.
              * This is why there is not a <CODE>set</CODE> method for the value property.
              *
              * <p>
              * For example, to add a new item, do as follows:
              * <pre>
              *    getValue().add(newItem);
              * </pre>
              *
              *
              * <p>
              * Objects of the following type(s) are allowed in the list
              * {@link STEPProductInformation.Products.Product.Values.Value }
              *
              *
              */
             public List<STEPProductInformation.Products.Product.Values.Value> getValue() {
                 if (value == null) {
                     value = new ArrayList<STEPProductInformation.Products.Product.Values.Value>();
                 }
                 return this.value;
             }


             /**
              * <p>Java class for anonymous complex type.
              *
              * <p>The following schema fragment specifies the expected content contained within this class.
              *
              * <pre>
              * &lt;complexType>
              *   &lt;simpleContent>
              *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
              *       &lt;attribute name="AttributeID" type="{http://www.w3.org/2001/XMLSchema}string" />
              *       &lt;attribute name="UnitID" type="{http://www.w3.org/2001/XMLSchema}string" />
              *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
              *       &lt;attribute name="Derived" type="{http://www.w3.org/2001/XMLSchema}string" />
              *     &lt;/extension>
              *   &lt;/simpleContent>
              * &lt;/complexType>
              * </pre>
              *
              *
              */
             @XmlAccessorType(XmlAccessType.FIELD)
             @XmlType(name = "", propOrder = {})
             public static class Value {

                 @XmlValue
                 protected String value;
                 @XmlAttribute(name = "AttributeID")
                 protected String attributeID;
                 @XmlAttribute(name = "UnitID")
                 protected String unitID;
                 @XmlAttribute(name = "ID")
                 protected String id;
                 @XmlAttribute(name = "Derived")
                 protected String derived;

                 /**
                  * Gets the value of the value property.
                  *
                  * @return
                  *     possible object is
                  *     {@link String }
                  *
                  */
                 public String getValue() {
                     return value;
                 }

                 /**
                  * Sets the value of the value property.
                  *
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *
                  */
                 public void setValue(String value) {
                     this.value = value;
                 }

                 /**
                  * Gets the value of the attributeID property.
                  *
                  * @return
                  *     possible object is
                  *     {@link String }
                  *
                  */
                 public String getAttributeID() {
                     return attributeID;
                 }

                 /**
                  * Sets the value of the attributeID property.
                  *
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *
                  */
                 public void setAttributeID(String value) {
                     this.attributeID = value;
                 }

                 /**
                  * Gets the value of the unitID property.
                  *
                  * @return
                  *     possible object is
                  *     {@link String }
                  *
                  */
                 public String getUnitID() {
                     return unitID;
                 }

                 /**
                  * Sets the value of the unitID property.
                  *
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *
                  */
                 public void setUnitID(String value) {
                     this.unitID = value;
                 }

                 /**
                  * Gets the value of the id property.
                  *
                  * @return
                  *     possible object is
                  *     {@link String }
                  *
                  */
                 public String getID() {
                     return id;
                 }

                 /**
                  * Sets the value of the id property.
                  *
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *
                  */
                 public void setID(String value) {
                     this.id = value;
                 }

                 /**
                  * Gets the value of the derived property.
                  *
                  * @return
                  *     possible object is
                  *     {@link String }
                  *
                  */
                 public String getDerived() {
                     return derived;
                 }

                 /**
                  * Sets the value of the derived property.
                  *
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *
                  */
                 public void setDerived(String value) {
                     this.derived = value;
                 }

             }

         }

     }

 }

}
