/**
 * -----------------------------------------------------------------------
 * STAPLES, INC
 * -----------------------------------------------------------------------
 * (C) Copyright 2007 Staples, Inc.          All rights reserved.
 *
 * NOTICE:  All information contained herein or attendant hereto is,
 *          and remains, the property of Staples Inc.  Many of the
 *          intellectual and technical concepts contained herein are
 *          proprietary to Staples Inc. Any dissemination of this
 *          information or reproduction of this material is strictly
 *          forbidden unless prior written permission is obtained
 *          from Staples Inc.
 * -----------------------------------------------------------------------
 */
/*
 * File name     :   ConverterToFixLength
 * Creation Date :   
 * @author  	 :   
 * @version 1.0
 */ 


package com.staples.pim.base.common.bean;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;

public class DBAttributes {
	

    public static HashMap attrHashMap = new HashMap();
    private void init(){
    	SimpleDateFormat formatter2 = new SimpleDateFormat("yyyyMMddHHmmssSSSSSS"); 
    	String ReqestID = "PCM" + String.format("%27s", formatter2.format(new Date())).replace(' ', '0');
    	//attrHashMap.put("A0012", ReqestID);
    	   attrHashMap.put("A0012", "");
    	   attrHashMap.put("A0003", "Create New Item");
    	   attrHashMap.put("Request_Type", "Create New Item");
    	   attrHashMap.put("D0247", "");
    	   attrHashMap.put("D0246", "");
    	   attrHashMap.put("D0249", "");
    	   attrHashMap.put("D0248", "");
    	   attrHashMap.put("D0243", "");
    	   attrHashMap.put("D0242", "");
    	   attrHashMap.put("D0245", "");
    	   attrHashMap.put("D0244", "");
    	   attrHashMap.put("D0241", "");
    	   attrHashMap.put("D0240", "");
    	   attrHashMap.put("D0259", "");
    	   attrHashMap.put("D0258", "");
    	   attrHashMap.put("D0257", "");
    	   attrHashMap.put("D0256", "");
    	   attrHashMap.put("D0255", "");
    	   attrHashMap.put("D0254", "");
    	   attrHashMap.put("D0253", "");
    	   attrHashMap.put("D0252", "");
    	   attrHashMap.put("D0251", "");
    	   attrHashMap.put("D0250", "");
    	   attrHashMap.put("A0045", "");
    	   attrHashMap.put("A0045_RET", "");
    	   attrHashMap.put("A0045_NAD", "");
    	   attrHashMap.put("A0046", "");
    	   attrHashMap.put("A0046_RET", "");
    	   attrHashMap.put("A0046_NAD", "");
    	   attrHashMap.put("A0043", "");
    	   attrHashMap.put("A0195", "");
    	   attrHashMap.put("A0194", "");
    	   attrHashMap.put("D0225", "");
    	   attrHashMap.put("D0224", "");
    	   attrHashMap.put("D0227", "");
    	   attrHashMap.put("D0226", "");
    	   attrHashMap.put("D0229", "");
    	   attrHashMap.put("D0228", "");
    	   attrHashMap.put("D0221", "");
    	   attrHashMap.put("D0220", "");
    	   attrHashMap.put("D0223", "");
    	   attrHashMap.put("A0051", "");
    	   attrHashMap.put("D0222", "");
    	   attrHashMap.put("D0238", "");
    	   attrHashMap.put("D0237", "");
    	   attrHashMap.put("D0236", "");
    	   attrHashMap.put("D0235", "");
    	   attrHashMap.put("A0197", "");
    	   attrHashMap.put("D0239", "");
    	   attrHashMap.put("D0230", "");
    	   attrHashMap.put("D0234", "");
    	   attrHashMap.put("D0233", "");
    	   attrHashMap.put("D0232", "");
    	   attrHashMap.put("D0231", "");
    	   attrHashMap.put("A0174", "");
    	   attrHashMap.put("A0173", "");
    	   attrHashMap.put("A0172", "");
    	   attrHashMap.put("A0171", "");
    	   attrHashMap.put("A0069", "");
    	   attrHashMap.put("A0068", "");
    	   attrHashMap.put("A0067", "");
    	   attrHashMap.put("A0067_RET", "");
    	   attrHashMap.put("A0067_NAD", "");
    	   attrHashMap.put("D0194", "");
    	   attrHashMap.put("D0195", "");
    	   attrHashMap.put("A0075", "");
    	   attrHashMap.put("A0075_RET", "");
    	   attrHashMap.put("A0075_NAD", "");
    	   attrHashMap.put("D0196", "");
    	   attrHashMap.put("D0197", "");
    	   attrHashMap.put("A0070", "");
    	   attrHashMap.put("D0198", "");
    	   attrHashMap.put("A0071", "");
    	   attrHashMap.put("D0199", "");
    	   attrHashMap.put("D0099", "");
    	   attrHashMap.put("A0166", "");
    	   attrHashMap.put("A0167", "");
    	   attrHashMap.put("A0164", "");
    	   attrHashMap.put("A0165", "");
    	   attrHashMap.put("D0095", "");
    	   attrHashMap.put("D0096", "");
    	   attrHashMap.put("D0097", "");
    	   attrHashMap.put("A0168", "");
    	   attrHashMap.put("D0098", "");
    	   attrHashMap.put("A0169", "");
    	   attrHashMap.put("D0094", "");
    	   attrHashMap.put("D0093", "");
    	   attrHashMap.put("D0092", "");
    	   attrHashMap.put("D0091", "");
    	   attrHashMap.put("D0090", "");
    	   attrHashMap.put("D0193", "");
    	   attrHashMap.put("A0077", "");
    	   attrHashMap.put("A0077_RET", "");
    	   attrHashMap.put("A0077_NAD", "");
    	   attrHashMap.put("A0076", "");
    	   attrHashMap.put("D0192", "");
    	   attrHashMap.put("D0191", "");
    	   attrHashMap.put("A0078", "");
    	   attrHashMap.put("A0078_RET", "");
    	   attrHashMap.put("A0078_NAD", "");
    	   attrHashMap.put("D0190", "");
    	   attrHashMap.put("A0083", "");
    	   attrHashMap.put("D0185", "");
    	   attrHashMap.put("A0084", "");
    	   attrHashMap.put("D0186", "");
    	   attrHashMap.put("A0085", "");
    	   attrHashMap.put("A0498", "");
    	   attrHashMap.put("D0183", "");
    	   attrHashMap.put("D0184", "");
    	   attrHashMap.put("A0086", "");
    	   attrHashMap.put("D0189", "");
    	   attrHashMap.put("A0080", "");
    	   attrHashMap.put("A0497", "");
    	   attrHashMap.put("A0497_RET", "");
    	   attrHashMap.put("A0497_NAD", "");
    	   attrHashMap.put("D0187", "");
    	   attrHashMap.put("A0082", "");
    	   attrHashMap.put("D0188", "");
    	   attrHashMap.put("A0175", "");
    	   attrHashMap.put("D0088", "");
    	   attrHashMap.put("A0177", "");
    	   attrHashMap.put("D0089", "");
    	   attrHashMap.put("A0178", "");
    	   attrHashMap.put("D0087", "");
    	   attrHashMap.put("A0152", "");
    	   attrHashMap.put("A0151", "");
    	   attrHashMap.put("A0150", "");
    	   attrHashMap.put("D0270", "");
    	   attrHashMap.put("A0092", "");
    	   attrHashMap.put("D0260", "");
    	   attrHashMap.put("D0261", "");
    	   attrHashMap.put("A0093", "");
    	   attrHashMap.put("D0262", "");
    	   attrHashMap.put("A0090", "");
    	   attrHashMap.put("D0263", "");
    	   attrHashMap.put("A0091", "");
    	   attrHashMap.put("D0264", "");
    	   attrHashMap.put("A0096", "");
    	   attrHashMap.put("D0265", "");
    	   attrHashMap.put("A0097", "");
    	   attrHashMap.put("D0266", "");
    	   attrHashMap.put("A0094", "");
    	   attrHashMap.put("D0267", "");
    	   attrHashMap.put("A0095", "");
    	   attrHashMap.put("D0268", "");
    	   attrHashMap.put("A0148", "");
    	   attrHashMap.put("D0269", "");
    	   attrHashMap.put("A0149", "");
    	   attrHashMap.put("A0146", "");
    	   attrHashMap.put("A0147", "");
    	   attrHashMap.put("A0144", "");
    	   attrHashMap.put("A0145", "");
    	   attrHashMap.put("A0142", "");
    	   attrHashMap.put("A0143", "");
    	   attrHashMap.put("A0161", "");
    	   attrHashMap.put("A0160", "");
    	   attrHashMap.put("A0163", "");
    	   attrHashMap.put("A0162", "");
    	   attrHashMap.put("A0099", "");
    	   attrHashMap.put("A0098", "");
    	   attrHashMap.put("D0273", "");
    	   attrHashMap.put("D0274", "");
    	   attrHashMap.put("D0271", "");
    	   attrHashMap.put("D0272", "");
    	   attrHashMap.put("D0275", "");
    	   attrHashMap.put("D0276", "");
    	   attrHashMap.put("A0157", "");
    	   attrHashMap.put("A0158", "");
    	   attrHashMap.put("A0159", "");
    	   attrHashMap.put("A0153", "");
    	   attrHashMap.put("A0154", "");
    	   attrHashMap.put("A0155", "");
    	   attrHashMap.put("A0156", "");
    	   attrHashMap.put("D0159", "");
    	   attrHashMap.put("D0158", "");
    	   attrHashMap.put("D0153", "");
    	   attrHashMap.put("D0152", "");
    	   attrHashMap.put("D0151", "");
    	   attrHashMap.put("D0150", "");
    	   attrHashMap.put("D0157", "");
    	   attrHashMap.put("D0156", "");
    	   attrHashMap.put("D0155", "");
    	   attrHashMap.put("D0154", "");
    	   attrHashMap.put("D0160", "");
    	   attrHashMap.put("D0045", "");
    	   attrHashMap.put("D0148", "");
    	   attrHashMap.put("D0044", "");
    	   attrHashMap.put("D0147", "");
    	   attrHashMap.put("D0047", "");
    	   attrHashMap.put("D0046", "");
    	   attrHashMap.put("D0149", "");
    	   attrHashMap.put("D0041", "");
    	   attrHashMap.put("D0040", "");
    	   attrHashMap.put("A0244", "");
    	   attrHashMap.put("D0043", "");
    	   attrHashMap.put("A0243", "");
    	   attrHashMap.put("D0042", "");
    	   attrHashMap.put("D0140", "");
    	   attrHashMap.put("D0142", "");
    	   attrHashMap.put("A0342", "");
    	   attrHashMap.put("D0141", "");
    	   attrHashMap.put("D0049", "");
    	   attrHashMap.put("D0144", "");
    	   attrHashMap.put("D0048", "");
    	   attrHashMap.put("D0143", "");
    	   attrHashMap.put("D0146", "");
    	   attrHashMap.put("D0145", "");
    	   attrHashMap.put("D0032", "");
    	   attrHashMap.put("D0031", "");
    	   attrHashMap.put("D0030", "");
    	   attrHashMap.put("A0237", "");
    	   attrHashMap.put("D0036", "");
    	   attrHashMap.put("D0035", "");
    	   attrHashMap.put("D0034", "");
    	   attrHashMap.put("D0033", "");
    	   attrHashMap.put("D0179", "");
    	   attrHashMap.put("D0178", "");
    	   attrHashMap.put("D0039", "");
    	   attrHashMap.put("A0239", "");
    	   attrHashMap.put("D0177", "");
    	   attrHashMap.put("D0038", "");
    	   attrHashMap.put("D0176", "");
    	   attrHashMap.put("A0238", "");
    	   attrHashMap.put("D0037", "");
    	   attrHashMap.put("D0181", "");
    	   attrHashMap.put("D0182", "");
    	   attrHashMap.put("D0180", "");
    	   attrHashMap.put("A0240", "");
    	   attrHashMap.put("A0220", "");
    	   attrHashMap.put("D0021", "");
    	   attrHashMap.put("D0020", "");
    	   attrHashMap.put("D0023", "");
    	   attrHashMap.put("D0169", "");
    	   attrHashMap.put("D0022", "");
    	   attrHashMap.put("D0025", "");
    	   attrHashMap.put("D0024", "");
    	   attrHashMap.put("D0166", "");
    	   attrHashMap.put("D0027", "");
    	   attrHashMap.put("D0165", "");
    	   attrHashMap.put("D0026", "");
    	   attrHashMap.put("D0168", "");
    	   attrHashMap.put("D0029", "");
    	   attrHashMap.put("D0167", "");
    	   attrHashMap.put("D0028", "");
    	   attrHashMap.put("D0162", "");
    	   attrHashMap.put("D0161", "");
    	   attrHashMap.put("D0164", "");
    	   attrHashMap.put("D0163", "");
    	   attrHashMap.put("D0170", "");
    	   attrHashMap.put("D0171", "");
    	   attrHashMap.put("A0310", "");
    	   attrHashMap.put("D0019", "");
    	   attrHashMap.put("A0313", "");
    	   attrHashMap.put("D0017", "");
    	   attrHashMap.put("D0112", "");
    	   attrHashMap.put("A0314", "");
    	   attrHashMap.put("D0018", "");
    	   attrHashMap.put("D0113", "");
    	   attrHashMap.put("D0210", "");
    	   attrHashMap.put("A0311", "");
    	   attrHashMap.put("D0211", "");
    	   attrHashMap.put("D0110", "");
    	   attrHashMap.put("A0312", "");
    	   attrHashMap.put("D0212", "");
    	   attrHashMap.put("D0111", "");
    	   attrHashMap.put("D0213", "");
    	   attrHashMap.put("D0116", "");
    	   attrHashMap.put("D0214", "");
    	   attrHashMap.put("D0117", "");
    	   attrHashMap.put("A0315", "");
    	   attrHashMap.put("D0215", "");
    	   attrHashMap.put("A0212", "");
    	   attrHashMap.put("D0114", "");
    	   attrHashMap.put("D0011", "");
    	   attrHashMap.put("A0316", "");
    	   attrHashMap.put("D0216", "");
    	   attrHashMap.put("D0115", "");
    	   attrHashMap.put("D0217", "");
    	   attrHashMap.put("D0218", "");
    	   attrHashMap.put("A0211", "");
    	   attrHashMap.put("D0219", "");
    	   attrHashMap.put("D0118", "");
    	   attrHashMap.put("D0119", "");
    	   attrHashMap.put("A0017", "");
    	   attrHashMap.put("A0119", "");
    	   attrHashMap.put("A0118", "");
    	   attrHashMap.put("A0117", "");
    	   attrHashMap.put("A0013", "");
    	   attrHashMap.put("A0013_RET", "");
    	   attrHashMap.put("A0013_NAD", "");
    	   attrHashMap.put("A0112", "");
    	   attrHashMap.put("A0111", "");
    	   attrHashMap.put("A0110", "");
    	   attrHashMap.put("A0116", "");
    	   attrHashMap.put("A0115", "");
    	   attrHashMap.put("A0114", "");
    	   attrHashMap.put("A0113", "");
    	   attrHashMap.put("D0200", "");
    	   attrHashMap.put("D0201", "");
    	   attrHashMap.put("D0100", "");
    	   attrHashMap.put("D0101", "");
    	   attrHashMap.put("A0302", "");
    	   attrHashMap.put("D0102", "");
    	   attrHashMap.put("D0103", "");
    	   attrHashMap.put("D0204", "");
    	   attrHashMap.put("D0205", "");
    	   attrHashMap.put("D0104", "");
    	   attrHashMap.put("D0202", "");
    	   attrHashMap.put("D0105", "");
    	   attrHashMap.put("A0307", "");
    	   attrHashMap.put("D0203", "");
    	   attrHashMap.put("D0106", "");
    	   attrHashMap.put("A0308", "");
    	   attrHashMap.put("D0208", "");
    	   attrHashMap.put("D0107", "");
    	   attrHashMap.put("A0309", "");
    	   attrHashMap.put("D0209", "");
    	   attrHashMap.put("D0108", "");
    	   attrHashMap.put("D0206", "");
    	   attrHashMap.put("D0109", "");
    	   attrHashMap.put("D0207", "");
    	   attrHashMap.put("A0107", "");
    	   attrHashMap.put("A0106", "");
    	   attrHashMap.put("A0109", "");
    	   attrHashMap.put("A0108", "");
    	   attrHashMap.put("A0101", "");
    	   attrHashMap.put("A0100", "");
    	   attrHashMap.put("A0103", "");
    	   attrHashMap.put("A0102", "");
    	   attrHashMap.put("A0105", "");
    	   attrHashMap.put("A0104", "");
    	   attrHashMap.put("A0140", "");
    	   attrHashMap.put("D0134", "");
    	   attrHashMap.put("D0135", "");
    	   attrHashMap.put("A0141", "");
    	   attrHashMap.put("D0132", "");
    	   attrHashMap.put("D0133", "");
    	   attrHashMap.put("D0130", "");
    	   attrHashMap.put("D0131", "");
    	   attrHashMap.put("A0339", "");
    	   attrHashMap.put("D0138", "");
    	   attrHashMap.put("D0139", "");
    	   attrHashMap.put("D0136", "");
    	   attrHashMap.put("D0137", "");
    	   attrHashMap.put("A0139", "");
    	   attrHashMap.put("A0138", "");
    	   attrHashMap.put("A0137", "");
    	   attrHashMap.put("A0136", "");
    	   attrHashMap.put("A0135", "");
    	   attrHashMap.put("A0134", "");
    	   attrHashMap.put("D0121", "");
    	   attrHashMap.put("A0323", "");
    	   attrHashMap.put("D0122", "");
    	   attrHashMap.put("A0324", "");
    	   attrHashMap.put("D0123", "");
    	   attrHashMap.put("D0124", "");
    	   attrHashMap.put("A0130", "");
    	   attrHashMap.put("D0120", "");
    	   attrHashMap.put("D0129", "");
    	   attrHashMap.put("D0125", "");
    	   attrHashMap.put("D0126", "");
    	   attrHashMap.put("D0127", "");
    	   attrHashMap.put("D0128", "");
    	   attrHashMap.put("A0128", "");
    	   attrHashMap.put("A0125", "");
    	   attrHashMap.put("A0124", "");
    	   attrHashMap.put("A0127", "");
    	   attrHashMap.put("A0126", "");
    	   attrHashMap.put("A0121", "");
    	   attrHashMap.put("A0120", "");
    	   attrHashMap.put("A0123", "");
    	   attrHashMap.put("A0122", "");
    	   attrHashMap.put("A0027", "");
    	   attrHashMap.put("A0028", "");
    	   attrHashMap.put("A0025", "");
    	   attrHashMap.put("A0026", "");
    	   attrHashMap.put("A0024", "");
    	   attrHashMap.put("A0254", "");
    	   attrHashMap.put("D0015", "");
    	   attrHashMap.put("D0016", "");
    	   attrHashMap.put("A0022", "");
    	   attrHashMap.put("A0214", "");
    	   attrHashMap.put("D0013", "");
    	   attrHashMap.put("D0014", "");
    	   attrHashMap.put("A0318", "");
    	   attrHashMap.put("D0012", "");
    	   attrHashMap.put("A0213", "");
    	   attrHashMap.put("A0210", "");
    	   attrHashMap.put("A0029", "");
    	   attrHashMap.put("A0066", "");
    	   attrHashMap.put("A0404", "");
    	   attrHashMap.put("A0065", "");
    	   attrHashMap.put("A0015", "");
    	   attrHashMap.put("A0011", "");
    	   attrHashMap.put("A0030", "");
    	   attrHashMap.put("A0018", "");
    	   attrHashMap.put("A0018_RET", "");
    	   attrHashMap.put("A0018_NAD", "");
    	   attrHashMap.put("A0036", "");
    	   attrHashMap.put("A0037", "");
    	   attrHashMap.put("A0181", "");
    	   attrHashMap.put("A0248", "");
    	   attrHashMap.put("A0180", "");
    	   attrHashMap.put("A0183", "");
    	   attrHashMap.put("A0182", "");
    	   attrHashMap.put("A0301", "");
    	   attrHashMap.put("A0241", "");
    	   attrHashMap.put("D0005", "");
    	   attrHashMap.put("A0185", "");
    	   attrHashMap.put("A0184", "");
    	   attrHashMap.put("D0007", "");
    	   attrHashMap.put("A0304", "");
    	   attrHashMap.put("A0251", "");
    	   attrHashMap.put("D0086", "");
    	   attrHashMap.put("A0008", "");
    	   attrHashMap.put("A0179", "");
    	   attrHashMap.put("A0007", "");
    	   attrHashMap.put("D0085", "");
    	   attrHashMap.put("A0230", "");
    	   attrHashMap.put("D0175", "");
    	   attrHashMap.put("A0191", "");
    	   attrHashMap.put("D0174", "");
    	   attrHashMap.put("D0173", "");
    	   attrHashMap.put("A0190", "");
    	   attrHashMap.put("A0189", "");
    	   attrHashMap.put("A0186", "");
    	   attrHashMap.put("A0052", "");
    	   attrHashMap.put("A0320", "");
    	   attrHashMap.put("A0410", "");
    	   attrHashMap.put("A0016", "");
    	   attrHashMap.put("A0038", "");
    	   attrHashMap.put("A0231", "");
    	   attrHashMap.put("A0224", "");
    	   attrHashMap.put("A0033", "");
    	   attrHashMap.put("A0081", "");
    	   attrHashMap.put("A0234", "");
    	   attrHashMap.put("A0217", "");
    	   attrHashMap.put("A0431", "");
    	   attrHashMap.put("A0031", "");
    	   attrHashMap.put("A0020", "");
    	   attrHashMap.put("A0042", "");
    	   attrHashMap.put("A0229", "");
    	 // start: merged with sprint_A3
    	   		//Boomerang output need
    	   attrHashMap.put("D0285", "");
    	   attrHashMap.put("Boomerang_Trigger", "");
    	   attrHashMap.put("A0501", "");
    	   attrHashMap.put("Web_Super_Category", "");
    	   attrHashMap.put("Web_Category", "");
    	   attrHashMap.put("Web_Department", "");
    	   attrHashMap.put("Web_Class", "");
    	   attrHashMap.put("Web_Class_ID", "");
    	   attrHashMap.put("STEP_Item_ID", "");
    	   attrHashMap.put("Product_Specialist", ""); 
    	  // end:  merged with sprint_A3
    	   attrHashMap.put("A0506", "");
    	   attrHashMap.put("A0507", "");
    	   attrHashMap.put("A0508", "");
    	   attrHashMap.put("A0509", "");
    	   attrHashMap.put("A0516", "");
    	   //new Attributes
    	   attrHashMap.put("A0499", "");
    	   attrHashMap.put("A0504", "");
    	   attrHashMap.put("A0500", "");
    	   attrHashMap.put("A0002", "");
    	   attrHashMap.put("A0537", "");
    }
    
    public DBAttributes() {
    	init();
    }

	public HashMap getAttrHashMap() {
		return attrHashMap;
	}
	public static String getAttrValue(String attrName) {
		String value = "";
		if (attrHashMap.get(attrName) != null){
			value = (String)attrHashMap.get(attrName);
			//if (value.length()>40){
			//	value = value.substring(0, 39);
			//}
		}
		 
		return value;
	}



}
